<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lvkacheln"
 *
 * Auto generated by Extension Builder 2016-07-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Kacheln',
	'description' => '',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '7.6',
			'fluid' => '7.6',
			'typo3' => '7.6',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);